spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mydb

  application:
    name: PRODUCT-SERVICE

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka